// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7c8wjTQL9gppk4JZq2_kRs9CtNeQP544',
    appId: '1:576664628290:web:be9e6ea2d6c6f2600451db',
    messagingSenderId: '576664628290',
    projectId: 'pblms-acd36',
    authDomain: 'pblms-acd36.firebaseapp.com',
    storageBucket: 'pblms-acd36.firebasestorage.app',
    measurementId: 'G-3TT3PLE3XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCULGA2ortJVc7B47NyfYC-hxpb2oMPdmA',
    appId: '1:576664628290:android:c5ef9058da8c3d060451db',
    messagingSenderId: '576664628290',
    projectId: 'pblms-acd36',
    storageBucket: 'pblms-acd36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu0359Y9BQMlgZjdJaxwHDs1JUv--n8mQ',
    appId: '1:576664628290:ios:7ccfdfb9a46789c10451db',
    messagingSenderId: '576664628290',
    projectId: 'pblms-acd36',
    storageBucket: 'pblms-acd36.firebasestorage.app',
    iosBundleId: 'com.example.portfoliobuilderslms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu0359Y9BQMlgZjdJaxwHDs1JUv--n8mQ',
    appId: '1:576664628290:ios:7ccfdfb9a46789c10451db',
    messagingSenderId: '576664628290',
    projectId: 'pblms-acd36',
    storageBucket: 'pblms-acd36.firebasestorage.app',
    iosBundleId: 'com.example.portfoliobuilderslms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7c8wjTQL9gppk4JZq2_kRs9CtNeQP544',
    appId: '1:576664628290:web:8a8f18b7662fc34c0451db',
    messagingSenderId: '576664628290',
    projectId: 'pblms-acd36',
    authDomain: 'pblms-acd36.firebaseapp.com',
    storageBucket: 'pblms-acd36.firebasestorage.app',
    measurementId: 'G-2LNVJQW8G6',
  );

}